packages:
  - apps/*
  - packages/*

allowBuilds:
  '@tailwindcss/oxide': true
  aws-sdk: true
  esbuild: true
  sharp: true
  unrs-resolver: true

catalog:
  "@date-fns/tz": ^1.4.1
  date-fns: ^4.1.0
  drizzle-orm: ^0.45.2
  openapi-fetch: ^0.17.0
