/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "AfiniaIngestApi": {
      "type": "sst.aws.ApiGatewayV1"
      "url": string
    }
    "BASE_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DATABASE_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DISCORD_USER_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DISCORD_WEBHOOK_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "UP_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "UP_WEBHOOK_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "VAPID_PRIVATE_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "VAPID_PUBLIC_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}